=pod

=head1 NAME

Gtk2::api - Notes about differences between the perl and C APIs for Gtk+

=head1 ABSTRACT

The Gtk2 module attempts to stick as close as is reasonable to the C API,
to minimize the need to maintain documentation which is nearly a copy of
the C API reference documentation.  However, the world is not perfect, and
the mappings between C and perl are not as clean and predictable as you 
might wish.  Thus, this page documents the spots that are different between
the C and perl APIs for Gtk.

=head1 DESCRIPTION

FIXME This list isn't complete.

The canonical documentation is the C API reference at
http://developer.gnome.org/doc/API/gtk/ and
http://developer.gnome.org/doc/API/gdk/

=head1 BINDING BASICS

Anything listed as "deprecated" in the C API reference does not appear in the
bindings.  Many functions refer to C concepts which are alien to the bindings.
many things have replacements.

=head1 MISSING METHODS

=over

=item g_object_ref	=> no replacement

=item g_object_unref	=> no replacement

=item g_boxed_free	=> no replacement

the bindings do automatic memory management.  you never need to use these.

=item gtk_timeout_add    => Glib::Timeout->add

=item gtk_timeout_remove => Glib::Source->remove

=item gtk_idle_add       => Glib::Idle->add

=item gtk_idle_remove    => Glib::Source->remove

=item gtk_input_add      => Glib::IOChannel->add_watch

=item gtk_input_remove   => Glib::Source->remove

the gtk_* functions are deprecated in favor of the g_* ones.
Gtk2::Helper has a wrapper for Glib::IOChannel->add_watch which
makes it behave more like gtk_input_add.

=back


=head1 RENAMED METHODS

=over

=item gtk_aspect_frame_set	=> $aspect_frame->set_params

avoid a clash with $gobject->set

=back


=head1 DIFFERENT CALL SIGNATURES OR SEMANTICS

=over

=item Gtk2::TreeSelection::get_selected

in scalar context, returns $iter; in list context, returns ($iter, $model)

=item Gtk2::TreeSelection::get_selected_rows

returns @paths; model is not returned as documented in the C API.
to get the model, try $selection->get_tree_view->get_model.

=back

=head1 SEE ALSO

The canonical documentation is the C API reference at
http://developer.gnome.org/doc/API/gtk/ and
http://developer.gnome.org/doc/API/gdk/

There should be a similar document for Glib --- link to it here when it exists.

=head1 AUTHOR

muppet E<lt>scott at asofyet dot orgE<gt>

=cut
